# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['desktop_app.py'],
    pathex=[],
    binaries=[
    (r'.venv\Lib\site-packages\websockets\speedups.cp314-win_amd64.pyd', 'websockets'),
    (r'.venv\Lib\site-packages\grpc\_cython\cygrpc.cp314-win_amd64.pyd', 'grpc\_cython'),
],
    datas=[
    ('assets', 'assets'),
    ('ui', 'ui'),
    ('.env', '.'),
    ('tts_credentials.json', '.'),
    (r'.venv\Lib\site-packages\google\cloud\texttospeech', r'google\cloud\texttospeech'),
    (r'.venv\Lib\site-packages\google\cloud\texttospeech_v1', r'google\cloud\texttospeech_v1'),
],
    hiddenimports=[
    "websockets",
    "websockets.legacy",
    "websockets.legacy.client",
    "websockets.legacy.server",
    "websockets.connection",
    "websockets.client",
    "websockets.server",
    "websockets.frames",
    "websockets.http11",
    "websockets.streams",
    "websockets.exceptions",
    "websockets.speedups",
    "google.cloud.texttospeech",
    "google.cloud.texttospeech_v1",
    "google.cloud.texttospeech_v1.services",
    "google.cloud.texttospeech_v1.services.text_to_speech",
    "google.cloud.texttospeech_v1.types",
    "grpc",
    "grpc._cython",
    "grpc._cython.cygrpc",
],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='OpenSight',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
