// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6KF0twHGvckbS2kEWoM5cP90iLg5vmXw',
    appId: '1:348346331222:web:4249cdfdbfa62441ad8bf7',
    messagingSenderId: '348346331222',
    projectId: 'gdg-search-492804',
    authDomain: 'gdg-search-492804.firebaseapp.com',
    storageBucket: 'gdg-search-492804.firebasestorage.app',
    measurementId: 'G-4XSKGWXDVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCutGl8qERRLNoDelB6unuwhVtJ1YSye5s',
    appId: '1:348346331222:android:6bcc4884bfc24cafad8bf7',
    messagingSenderId: '348346331222',
    projectId: 'gdg-search-492804',
    storageBucket: 'gdg-search-492804.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHRBLqhBUBK6aF2vpA4k8Y-Ay1LzGnlfU',
    appId: '1:348346331222:ios:d329a0a078f78b94ad8bf7',
    messagingSenderId: '348346331222',
    projectId: 'gdg-search-492804',
    storageBucket: 'gdg-search-492804.firebasestorage.app',
    iosBundleId: 'com.example.voiceClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHRBLqhBUBK6aF2vpA4k8Y-Ay1LzGnlfU',
    appId: '1:348346331222:ios:d329a0a078f78b94ad8bf7',
    messagingSenderId: '348346331222',
    projectId: 'gdg-search-492804',
    storageBucket: 'gdg-search-492804.firebasestorage.app',
    iosBundleId: 'com.example.voiceClient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6KF0twHGvckbS2kEWoM5cP90iLg5vmXw',
    appId: '1:348346331222:web:9c06d9329aa56874ad8bf7',
    messagingSenderId: '348346331222',
    projectId: 'gdg-search-492804',
    authDomain: 'gdg-search-492804.firebaseapp.com',
    storageBucket: 'gdg-search-492804.firebasestorage.app',
    measurementId: 'G-E6D4LPQL1M',
  );
}
